title: pœlitics
description: poelitics.org is a research blog and a collection of side projects by Kaspar Ravel, researcher in tactical new media, teacher and resident artist at Sorbonne University.
theme: minima
