title: Pœlitics
description: poelitics.org is a research blog and a collection of side projects by Kaspar Ravel, a researcher in tactical new media, teacher and resident artist at Sorbonne University.
theme: minima
