title: Poelitics
description: Hi, my name is Kaspar Ravel (they/them). I am a researcher in tactical new media, a teacher and an artist. I design and employ safe(r) technologies to tackle contemporary societal issues. I work collaboratively with schools, embassys, politics, NGOs, designers and activists, helping them develop tools to short-circuit the technology that surrounds us and inspire alternative forms of digital literacy.
theme: minima
