title: Poelitics
description: Kaspar Ravel (they/them) is a researcher in tactical new media, a teacher and an artist. They design and employ safe(r) technologies to tackle contemporary societal issues. They work collaboratively with schools, embassys, politics, NGOs, designers and activists, helping them develop tools to short-circuit the technology that surrounds us and inspire alternative forms of digital literacy.
theme: minima
